In [138]:
hash(1)

1

In [139]:
hash(1.0)

1

In [4]:
hash(1.2)

461168601842738689

In [5]:
hash("a")

-6811454452911508895

In [6]:
list1= [1, 2, 3]
list2= list1
list3= list1[:]
list1.append(4)

In [7]:
id(list1)

2005034669312

In [8]:
id(list2)

2005034669312

In [9]:
id(list3)

2005034996032

In [10]:
a=256
b=256
id(a)


140717034523520

In [11]:
id(b)

140717034523520

In [20]:
if Ellipsis != True:
    print("True")

True


In [16]:
a=...#逻辑值为true
print(a)

Ellipsis


In [8]:
print(10 % 3)
print(-10 % 3)
print(-10//3)
print(10//3)
print(bin(-5))
print(bin(5))
print(bin(3))
print(5 | 3)


1
2
-4
3
-0b101
0b101
0b11
7


In [20]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)
arr[0,1,:]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


array([4, 5, 6])

In [149]:
d0=dict.fromkeys(range(5),1)
print(id(d0[0]),id(d0[1]))
d0[0]=2
print(d0)





print("--------------------")
del d0[0]
print(id(d0))

print(id(d0.get(0)),id(d0))
print(id(None))

140719402331040 140719402331040
{0: 2, 1: 1, 2: 1, 3: 1, 4: 1}
--------------------
2682726585600
140719402166512 2682726585600
140719402166512


In [15]:
a={"a":1,"b":2}
a["a"]=input() or a["a"]#0的bool值是False，""空字符串的bool值也是False，其他都是True

print(a)

{'a': 1, 'b': 2}


In [21]:
b=[None]
print(b)
print(bool(b))

[None]
True
